use_frameworks!

platform :ios, '9.0'

target 'podPrivateDemo_Example' do
  pod 'podPrivateDemo', :path => '../'

  target 'podPrivateDemo_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
